kind: Service
apiVersion: v1
metadata:
  name: echoclient
spec:
  type: NodePort
  selector:
    app: echoclient
  ports:
  - name: rpc
    protocol: TCP
    port: 4000
    targetPort: 4000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoclient
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoclient
    spec:
      containers:
      - name: echoclient
        image: lb-example-client:1
        imagePullPolicy: IfNotPresent
        ports:
        - name: rpc
          containerPort: 4000
          protocol: TCP
