kind: Service
apiVersion: v1
metadata:
  name: echoserver
spec:
  clusterIP: None
  selector:
    app: echoserver
  ports:
  - name: rpc
    protocol: TCP
    port: 4000
    targetPort: 4000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: lb-example-server:latest
        imagePullPolicy: IfNotPresent
        command:
        - /service/app
        ports:
        - name: rpc
          containerPort: 4000
          protocol: TCP
